# Configuration for odoo setup

# Name of the odoo application
name: odoo

# Service definitions for the odoo application
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8100:80"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass

# CasaOS specific configuration
x-casaos:
  # Supported CPU architectures for the application
  architectures:
    - amd64
    - arm
  # Main service of the application
  main: app
  description:
    # Description in English
    en_us: Odoo, an open source suite of business apps, emcompasses various functionalities to cater to your company's requirements. It features include CRM, eCommerce, accounting, inventory management, point of sale, project management, and more.
  tagline:
    # Short description or tagline in English
    en_us: Odoo-open source business apps for all needs
  # Developer's name or identifier
  developer: "Automattic"
  # Author of this configuration
  author: Mypancho.com
  # Icon for the application
  icon: https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/odoo/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/odoo/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/odoo/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/mypancho/Pancho-Cloud-App-Store@main/Apps/odoo/screenshot-3.png
  # Thumbnail image
  thumbnail: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bazarr/thumbnail.png
  title:
    # Title in English
    en_us: odoo
  # Application category
  category: project-management
  # Port mapping information
  port_map: "8100"
