version: '2'
services:
  freepbx:
#    build: .
    image: mima84/docker-freepbx
    container_name: freepbx

#    network_mode: "host"
    ports:
    - "5160-5161:5160-5161/udp"
    - "5060-5060:5060-5060/udp"
    - "8082:8082/tcp"
    - "10000-10050:10000-10050/udp"
    
    volumes:
      - freepbx-apache:/etc/apache2
      - freepbx-asterisk-config:/etc/asterisk
      - freepbx-mysql:/var/lib/mysql
      - freepbx-asterisk-spool:/var/spool/asterisk
      - freepbx-asterisk-data:/var/lib/asterisk

volumes:
  freepbx-apache:
  freepbx-asterisk-config:
  freepbx-mysql:
  freepbx-asterisk-spool:
  freepbx-asterisk-data:

x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
