version: '3'

services:
  freepbx:
    image: quay.io/arkadi/sangoma
    ports:
      - "80:80"
      - "5060:5060"
      - "4569:4569"
      - "5061:5061"
      - "5160:5160"
      - "5161:5161"
      - "4568:4568"
      - "83:83"
      - "5555:5555"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - ASTERISK_DB_PW=password
      - ASTERISK_DB_USER=root
      - ASTERISK_DB_PW_ROOT=asterisk
      - ASTERISK_DB_PW_USER=password
      - MYSQL_PASSWORD=password
    volumes:
      - /var/lib/asterisk:/var/lib/asterisk
      - /etc/asterisk:/etc/asterisk
      - /var/lib/mysql:/var/lib/mysql
      - /var/log/asterisk:/var/log/asterisk
      - /tftpboot:/tftpboot
      - /etc/amportal.conf:/etc/amportal.conf
      - /etc/asterisk/voicemail.conf:/etc/asterisk/voicemail.conf
    restart: always
    
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
