version: "3.3"

services:

  freepbx:
    image: freepbx/freepbx:latest
    ports:
      - "8088:80"
      - "4443:443" 
    environment:
      PUBLIC_IP: 192.168.1.10
    volumes:  
      - /docker/appdata/freepbx:/var/lib/asterisk
    restart: unless-stopped
  
  db:  
    image: freepbx/mariadb
    restart: always
    volumes:
      - /docker/appdata2/freepbx:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password123
      
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
