version: '2'

services:
  freepbx:
    image: 'sipxcom/freepbx'
    ports:
      - '5060:5060/udp'
      - '5060:5060/tcp'
      - '5160:5160/udp'
      - '5160:5160/tcp'
      - '18000-18100:18000-18100/udp'
    environment:
      - 'DB_HOST=db'
      - 'DB_USER=freepbxuser'
      - 'DB_PASS=password'
      - 'ASTERISK_DB_PW=asterisk'
    restart: always

  db:
    image: 'mariadb'
    environment:
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_DATABASE=freepbx'
      - 'MYSQL_USER=freepbxuser'
      - 'MYSQL_PASSWORD=password'
    restart: always

  web:
    image: 'php:apache'
    volumes:
      - '/var/www/html:/var/www/html'
    restart: always
    depends_on:
      - db
      - freepbx
      
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
