version: '3.5'

services:
  freepbx:
    image: linuxserver/freepbx
    container_name: freepbx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /path/to/local/config:/config
    ports:
      - 8080:80
      - 5060:5060/udp
      - 5160:5160/udp
      - 4569:4569/udp
    restart: unless-stopped
    
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
