version: "3.7"

services:

  freepbx:
    image: freepbx/freepbx:latest
    ports:
      - "80:80"
      - "443:443"
      - "5060:5060"
      - "5061:5061"  
      - "10000-10200:10000-10200/udp"
    environment:
     - TZ="America/New_York"
    volumes:
      - /etc/localtime:/etc/localtime:ro  
      - /path/on/host:/var/lib/asterisk
    restart: always

volumes:
  freepbx_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/path/on/host'
networks:
  default:
    external:
      name: freepbx_network
    
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
