version: '3'

services:

  freepbx:
    image: sangoma/freepbx:latest
    ports:
      - "80:80"
      - "443:443"  
      - "5060:5060"
      - "5061:5061"
      - "10000-10200:10000-10200/udp"
    volumes:
      - /mnt/appdata/freepbx:/var/lib/asterisk
    environment:
      - TZ=America/New_York
    restart: always

  db: 
    image: mariadb:latest
    volumes:
      - /mnt/appdata/freepbx/mysql:/var/lib/mysql
    environment:  
      - MYSQL_ROOT_PASSWORD=amp111
      - MYSQL_DATABASE=asterisk
      - MYSQL_USER=asterisk 
      - MYSQL_PASSWORD=amp111
      
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
