version: "3.3"

services:
  freepbx:  
    image: tiredofit/freepbx:latest 
    ports:
      - "80:80"
      - "443:443"
      - "5060:5060"
      - "10000-10200:10000-10200/udp"
      
    volumes:
      - ./data:/config
      - /etc/localtime:/etc/localtime:ro

    environment:
      - PUID=1000 
      - PGID=1000
      - TZ=America/New_York

    restart: unless-stopped

volumes:
  data:
      
x-casaos:
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  tagline:
    en_us: FreePBX is a web based user interface designed to simplify management of Asterisk PBX.
  developer: Izpbx
  author: Mypancho.com
  icon: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/screenshot-3.png
  thumbnail: https://cdn.jsdelivr.net/gh/uche40/Dev-Pancho-Cloud-App-Store@main/Apps/freepbx/thumbnail.png
  title:
    en_us: freepbx
  category: Server
