name: wordpress
services:
  app:
    depends_on:
      - db
    image: wordpress:latest
    hostname: wordpress
    networks:
      - cloud
    deploy:
      resources:
        reservations:
          memory: 32M
    restart: always
    # Restart line controls the restart mode, meaning if the container stops running for any reason, it will restart the process immediately.
    ports:
      - "8080:80"
      # The previous line defines the port that the WordPress container will use. After successful installation, the full path will look like this: http://localhost:8000
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: MyWordPressUser
      WORDPRESS_DB_PASSWORD: Pa$$5w0rD
      WORDPRESS_DB_NAME: MyWordPressDatabaseName
# Similar to MySQL image variables, the last four lines define the main variables needed for the WordPress container to work properly with the MySQL container.
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/html
        target: /var/www/html
  db:
    image: mysql:latest
    hostname: db
    networks:
      - cloud
    deploy:
      resources:
        reservations:
          memory: 512M
    # image: mysql:5.7 indicates the MySQL database container image from Docker Hub used in this installation.
    restart: always
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/mysql
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyR00tMySQLPa$$5w0rD
      MYSQL_DATABASE: MyWordPressDatabaseName
      MYSQL_USER: MyWordPressUser
      MYSQL_PASSWORD: Pa$$5w0rD
      # Previous four lines define the main variables needed for the MySQL container to work: database, database username, database user password, and the MySQL root password.
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: "Welcome to WordPress, the web platform trusted by millions of businesses worldwide. If you're an SMB owner looking to make a big impact online, you're in the right place. WordPress is your all-in-one solution for building a powerful website that showcases your products, services, and brand with style and professionalism. 
    <br />
    With easy-to-use tools, customizable themes, and a supportive community, WordPress empowers you to create a website that grows with your business. Whether you're just starting or ready to expand your online presence, WordPress is here to help you succeed in the digital world."
  screenshot_link:
    - https://raw.githubusercontent.com/mypancho/PanchoOS-AppStore/main/Apps/WordPress/screenshot-1.png
    - https://raw.githubusercontent.com/mypancho/PanchoOS-AppStore/main/Apps/WordPress/screenshot-2.png
    - https://raw.githubusercontent.com/mypancho/PanchoOS-AppStore/main/Apps/WordPress/screenshot-3.png
    - https://raw.githubusercontent.com/mypancho/PanchoOS-AppStore/main/Apps/WordPress/screenshot-4.png
  tagline:
    en_us: A Free And Open-source CMS
  developer: 'Automatic'
  author: Pancho Inc
  icon: https://raw.githubusercontent.com/mypancho/PanchoOS-AppStore/main/Apps/WordPress/icon.png
  thumbnail: https://raw.githubusercontent.com/mypancho/PanchoOS-AppStore/main/Apps/WordPress/thumbnail.png
  tips:
    before_install:
      en_us: |
        For database connection, select `MySQL` then on the `database host` field put `db`, for `database user` put `root` and for `database password` put `casaos`
  title:
    en_us: Wordpress
  category: CMS
  port_map: '80'
  
